### ISSUE TITLE
Move all "data" to "asset" (if it's possible)

### ISSUE THREAD

**Issue by scips** [rtbfinfo/ilots-de-chaleur#3]
https://github.com/rtbfinfo/ilots-de-chaleur/blame/e476365aab995f6185ed0c03fd53dd95d27d3166/r%C3%A9colte-data/2-centroid-temperature.ipynb.ipynb#L74

**Comment by scips** [comment]
Est-ce que tu penses que c'est possible de mettre dans /assets/ les bons assets (toutes les villes en GeoTiff du coup? Historie que lorsqu'on lance le notebook, ça fonctionne directement?

**Comment by Yheloww** [comment]
voilà c'est fait, j'ai aussi rajouté les données de pourcentages de verdures (que j'ai eu en faisant une manip sur QGIS que je pourrait peut-être expliquer plus tard)
